; =========================================
;  NOTE!! Generated by GPT for stress testing the assembler
;  This code does absolutely nothing useful, its a PoC
; =========================================

.define SCREEN_W     640
.define SCREEN_H     480
.define BPP          4
.define FRAME_SIZE   #SCREEN_W * #SCREEN_H * #BPP

.define ZERO         0
.define MAGIC        0xCAFEBABE
.define TITLE        "Hello from FL32R!"

; redefine with intent
.define STRIDE 4
.undef  STRIDE
.define STRIDE 8


; =========================================
;  Data section
; =========================================

@data
vramFrontBuffer   .word  0x40000000
vramBackBuffer    .word  0x40000000 + #FRAME_SIZE

titleString       .asciz #TITLE
frameCounter      .word  0
sentinel          .word  #MAGIC


; =========================================
;  Code section
; =========================================

@text
start:
    ; load addresses (PC-relative, always safe)
    LD    RAX, $vramFrontBuffer
    LD    RBX, $vramBackBuffer

    ; copy one word to prove we can
    LDW   RCX, [RBX]
    STW   [RAX], RCX

    ; bump frame counter
    LD    RDX, $frameCounter
    LDW   R8,  [RDX]
    ADDI  R8,  1
    STW   [RDX], R8

    ; compare against sentinel
    LD    R9,  $sentinel
    LDW   R9,  [R9]

    LDI   R10, #MAGIC     ; immediates are fine in LDI
    CMP   R9,  R10
    JEQ   print_title

    KILL


print_title:
    ; show off string + offset addressing
    LEA   RAX, $titleString
    ADDI  RAX, #ZERO + 1   ; skip first char
    LDB   R7,  [RAX]

    ; pretend this does something meaningful
    INT   0x1
    KILL


; =========================================
;  Expression-heavy addressing demo
; =========================================

expr_demo:
    ; all of this is folded at assembly time
    LDB   R3, [RBX + (16 >> 1) + (4 * 5) / 2]
    STB   [RAX + (10 + 20 * 3)], R3
    JMP   start
